# Import libraries

In [1]:
# Standard code libraries
import faulthandler
import json
import re
from datetime import datetime as dt
from io import StringIO
from pathlib import Path
from typing import TYPE_CHECKING, cast

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# Custom code libraries from ReSurfEMG
from resurfemg.data_connector.config import ConfigCreatorWidget
from resurfemg.data_connector.file_discovery import find_files
from resurfemg.data_connector.tmsisdk_lite import Poly5Reader
from resurfemg.pipelines.ipy_widgets import DatasetSelector as ds  # noqa: N813
from resurfemg.pipelines.multimodal import MultimodalDataGroup

if TYPE_CHECKING:
    from resurfemg.data_connector.data_classes import (
        EmgDataGroup,
        VentilatorDataGroup,
    )

# from resurfemg.postprocessing import quality_assessment as qa

faulthandler.enable()

# %matplotlib widget
%matplotlib qt

from IPython.display import HTML


def show(df, n_rows=None, n_cols=None):
    with pd.option_context(
        "display.max_rows", n_rows, "display.max_columns", n_cols
    ):  # more options can be specified also
        display(HTML(df._repr_html_()))

# Discover files

In [ ]:
creator = ConfigCreatorWidget("config_IC.json")

In [ ]:
# Identify all recordings available
# for the selected patient/measurement_date

# Root directory for test data
config = creator.get_config()
root_patient_data_directory = config.get_directory("patient_data")


files = find_files(root_patient_data_directory)
# # _patient_regex = r"^([Pp]_?\d+)"  # note the ( ) around the patternprint(files)
_patient_regex = r"MST\d{3}"
# col = files["files"]

# ids = col.str.extract(_patient_regex, expand=False)
# dataset_dict = col.groupby(ids).apply(list).to_dict()

ps = ds(root_directory=root_patient_data_directory, patient_regex=_patient_regex)

In [ ]:
# import the protocol details

PS_PEEP_levels_df = pd.read_csv(
    "C:\\Users\\ManinettiC\\Documents\\Participant_Id measurement_date PS_level.csv",
    delimiter="\t",
)

PS_PEEP_levels_df.columns = PS_PEEP_levels_df.columns.str.replace(
    "PS_level_(cmH2O)_Step_", "PS_cmH2O_"
).str.replace("PS_Recording_nr_Step_", "PS_Recording_nr_")
PS_PEEP_levels_df.columns = PS_PEEP_levels_df.columns.str.replace(
    "PEEP_protocol_PEEP_level_(cmH2O)_Step_", "PEEP_cmH2O_"
).str.replace("PEEP_protocol_Recording_nr_Step_", "PEEP_Recording_nr_")

PS_dict = {}
levels = {
    "PS": ["minus_3", "0", "plus_3", "plus_6"],
    "PEEP": ["minus_2", "0", "plus_2", "plus_4"],
}

for row in PS_PEEP_levels_df.itertuples(index=False):
    patient_id = row.Participant_Id
    measurement_date = row.measurement_date
    for _type, _levels in levels.items():
        for level in _levels:
            if getattr(row, f"{_type}_cmH2O_{level}") is not None:
                _recording_nr = f"{getattr(row, f'{_type}_Recording_nr_{level}'):03d}"
                if patient_id not in PS_dict:
                    PS_dict[patient_id] = {}
                if measurement_date not in PS_dict[patient_id]:
                    PS_dict[patient_id][measurement_date] = {}
                if _recording_nr not in PS_dict[patient_id][measurement_date]:
                    PS_dict[patient_id][measurement_date][_recording_nr] = {}
                PS_dict[patient_id][measurement_date][_recording_nr]["cmH2O"] = getattr(
                    row, f"{_type}_cmH2O_{level}"
                )
                PS_dict[patient_id][measurement_date][_recording_nr]["level"] = level
                PS_dict[patient_id][measurement_date][_recording_nr]["protocol"] = _type

In [ ]:
# Add the filenames
# to the protocol details dictionary
dataset_dict = ps.dataset_dict
records = pd.DataFrame(columns=["patient", "day", "step", "PEEP"])
format_day = r"^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}$"
format_step = "([0-9]{3})"
for patient, record in dataset_dict.items():
    for _day, day_record in record.items():
        if not re.match(format_day, _day):
            print(
                f"Discarding '{_day}' for patient '{patient}'"
                f"as it does not match the expected format."
            )
            continue
        day = dt.strptime(_day, "%Y-%m-%d_%H-%M-%S").strftime("%d/%m/%Y")  # noqa: DTZ007
        for step, step_record in day_record.items():
            if not re.match(format_step, step):
                print(
                    f"Discarding '{step}' for patient '{patient}' on day '{day}'"
                    f"as it does not match the expected format."
                )
                continue
            # print(patient, day, step, record)
            try:
                for file in step_record:
                    _type = ps._guess_data_type(file)  # noqa: SLF001
                    _file = Path(ps.root_directory).joinpath(patient, _day, step, file)
                    PS_dict[patient][day][step][_type] = _file
            except Exception as e:  # noqa: BLE001
                print(f"Error occurred while processing file '{file}': {e}")  # type: ignore
                continue

In [ ]:
# export the protocol details
# dictionary to a JSON file

with Path.open(Path("C:\\Users\\ManinettiC\\Documents\\PS_dict.json"), "w") as f:
    json.dump(PS_dict, f, indent=4, default=str)

# Process files (auto)

In [ ]:
# try:
# from copy import deepcopy

PS_dict = json.load(Path.open(Path("C:\\Users\\ManinettiC\\Documents\\PS_dict.json")))
for patient, patient_record in PS_dict.items():
    for day, day_record in patient_record.items():
        for step, record in day_record.items():
            if "Ventilator" in record and "EMG" in record:
                protocol = record["protocol"]
                record_string = (
                    f"subject {patient}, protocol {protocol}, day {day}, "
                    f"step {step} ({record['cmH2O']} cmH2O)"
                )
                print(f"\033[94m Processing {record_string}")
                _d_temp = record.copy()
                dump_file = Path.joinpath(
                    Path("C:\\Users\\ManinettiC\\Documents\\TOPSPIN"),
                    patient,
                    protocol,
                    str.replace(day, "/", "_"),
                    f"{record['cmH2O']}cmH2O.json",
                )
                dump_file.parent.mkdir(parents=True, exist_ok=True)
                if dump_file.exists():
                    print("File already exists, skipping.")
                    continue
                try:
                    multimodal_data_group = MultimodalDataGroup(
                        cast(
                            "VentilatorDataGroup",
                            ds.get_data(
                                Poly5Reader(str(record["Ventilator"]), verbose=False),
                                "Ventilator",
                                verbose=False,
                            ),
                        ),
                        cast(
                            "EmgDataGroup",
                            ds.get_data(
                                Poly5Reader(str(record["EMG"]), verbose=False),
                                "EMG",
                                verbose=False,
                            ),
                        ),
                    )
                    multimodal_data_group.set_labels()
                    multimodal_data_group.process_emg()
                    multimodal_data_group.process_emg_breaths(trial=protocol)
                    if protocol == "PEEP":
                        try:
                            multimodal_data_group.process_ventilator_breaths(
                                trial=protocol
                            )
                            multimodal_data_group.link_breaths(trial=protocol)
                            multimodal_data_group.calculate_ETP(trial=protocol)
                            multimodal_data_group.calculate_PTP()
                            multimodal_data_group.compute_quality_criteria(
                                trial=protocol
                            )
                            peak_set_name = "Pocc"
                            vent_idx = multimodal_data_group.p_vent_idx
                        except Exception as e:
                            print(f"\033[93m >>>>> Error at {record_string}: {e}")
                            continue
                    else:
                        try:
                            multimodal_data_group.calculate_ETP(trial=protocol)
                            multimodal_data_group.compute_quality_criteria(
                                trial=protocol
                            )
                            multimodal_data_group.process_ventilator_breaths(
                                trial=protocol
                            )
                            multimodal_data_group.link_breaths(trial=protocol)
                            peak_set_name = "neural_breaths"
                            vent_idx = multimodal_data_group.v_vent_idx
                        except Exception as e:
                            print(f"\033[93m >>>>> Error at {record_string}: {e}")
                            continue

                    for df_name in [
                        "peak_df",
                        "quality_values_df",
                        "quality_outcomes_df",
                    ]:
                        if "vent" not in _d_temp:
                            _d_temp["vent"] = {}
                        _d_temp["vent"][df_name] = getattr(
                            multimodal_data_group.vent_timeseries[vent_idx].peaks[
                                peak_set_name
                            ],
                            df_name,
                        )
                        for idx in multimodal_data_group.emg_idx:
                            label = multimodal_data_group.emg_timeseries.labels[idx]
                            if label not in _d_temp:
                                _d_temp[label] = {}
                            _d_temp[label][df_name] = getattr(
                                multimodal_data_group.emg_timeseries[label].peaks[
                                    peak_set_name
                                ],
                                df_name,
                            )

                    with Path.open(Path(dump_file), "w") as f:
                        json.dump(_d_temp, f, indent=4, default=lambda df: df.to_json())
                    print(f"\033[92m >>>>> Successfully processed {record_string}")
                except Exception as e:
                    print(f"\033[93m >>>>> Error at {record_string}: {e}")
                    continue
# except Exception as e:
#     print(f">>>>> Error at {record_string}: {e}")

# Import results

For each protocol (PS, PEEP) and each measure (ventilator, EMGdi, EMGic), generate three dataframes: peak_df, quality_values_df, quality_outcomes_df. 
Each protocol's own dataframes, including the information about the patient, measurement day, and protocol settings, are iteratively appended to the corresponding comprehensive dataframe.

In [2]:
# load the trials dictionary
PS_dict = json.load(Path.open(Path("C:\\Users\\ManinettiC\\Documents\\PS_dict.json")))

In [3]:
measure_names = {
    "PS": ["vent", "EMGdi", "EMGic", "linked_breaths"],
    "PEEP": ["vent", "EMGdi", "EMGic"],
}

df_names = ["peak_df", "quality_values_df", "quality_outcomes_df"]
results_dict = {"PS": {}, "PEEP": {}}

for protocol_name, protocol_df_names in measure_names.items():
    for measure in protocol_df_names:
        results_dict[protocol_name][measure] = {}
        for df_name in df_names:
            results_dict[protocol_name][measure][df_name] = pd.DataFrame()

_trial_info = ["patient", "day", "step", "level"]
# _index =[[["info"]*len(_trial_info), ["percentage_valid_breaths"]*3], list(_trial_info) + measure_names["PS"]]
# _index = pd.MultiIndex.from_arrays(
#     [
#         [""] * len(_trial_info) + ["percentage_valid_breaths"] * len(measure_names["PS"]),
#         list(_trial_info) + measure_names["PS"],
#     ]
# )
cols_ps = [
    f"{prefix}{measure}"
    for prefix in ("valid_percentage_", "valid_breaths_", "tot_breaths_")
    for measure in measure_names["PS"]
]
trial_details = {
    "PS": pd.DataFrame(columns=_trial_info + cols_ps),
    "PEEP": pd.DataFrame(
        columns=_trial_info
        + ["valid_manoeuvers_" + meas for meas in measure_names["PEEP"]]
    ),
}

PS_dict = json.load(Path.open(Path("C:\\Users\\ManinettiC\\Documents\\PS_dict.json")))
for patient, patient_record in PS_dict.items():
    for day, day_record in patient_record.items():
        for step, record in day_record.items():
            if "Ventilator" in record and "EMG" in record:
                protocol = record["trial"]
                level = record["cmH2O"]
                record_string = (
                    f"patient {patient}, protocol {protocol}, day {day}, "
                    f"step {step} ({level} cmH2O)"
                )
                print(f"\033[94m Processing {record_string}")

                dump_file = Path.joinpath(
                    Path("C:\\Users\\ManinettiC\\Documents\\TOPSPIN_linked_legacy"),
                    patient,
                    protocol,
                    str.replace(day, "/", "_"),
                    f"{level}cmH2O.json",
                )
                if not dump_file.exists():
                    print(f"\033[91m >>>>> File {dump_file} does not exist, skipping.")
                    continue

                _d_temp = json.load(Path.open(Path(dump_file)))
                valid_percentage = {}
                valid_breaths = {}
                tot_breaths = {}
                for measure in measure_names[protocol]:
                    valid_percentage[measure] = None
                    for df_name in df_names:
                        _df_temp = pd.DataFrame()
                        if df_name not in _d_temp[measure]:
                            print(
                                f"\033[91m >>>>> DataFrame '{df_name}' not found in {dump_file}, skipping."
                            )
                            continue
                        _df_temp = pd.read_json(StringIO(_d_temp[measure][df_name]))
                        _df_temp["patient"] = patient
                        _df_temp["day"] = day
                        _df_temp["level"] = level
                        _df_temp["step"] = step
                        _d_temp[df_name] = _df_temp
                        results_dict[protocol][measure][df_name] = pd.concat(
                            [results_dict[protocol][measure][df_name], _df_temp],
                            ignore_index=True,
                        )
                        if df_name == "peak_df" and "valid" in _df_temp.columns:
                            valid = _df_temp["valid"]
                            tot_breaths[measure] = valid.count()
                            valid_breaths[measure] = valid[valid == 1].count()

                i = len(trial_details[protocol])

                if protocol == "PS":
                    for measure in measure_names["PS"]:
                        if measure == "linked_breaths":
                            continue
                        trial_details[protocol].loc[i, "tot_breaths_" + measure] = (
                            tot_breaths.get(measure, None)
                        )
                        trial_details[protocol].loc[i, "valid_breaths_" + measure] = (
                            valid_breaths.get(measure, None)
                        )
                        trial_details[protocol].loc[
                            i, "valid_percentage_" + measure
                        ] = (
                            valid_breaths.get(measure, None)
                            / tot_breaths.get("vent", 0)
                            * 100
                        )
                else:
                    for measure in measure_names["PEEP"]:
                        trial_details[protocol].loc[
                            i, "valid_manoeuvers_" + measure
                        ] = valid_breaths.get(measure, None)
                    trial_details[protocol].loc[i, "manoeuvers"] = sum(
                        [_tot for _tot in tot_breaths.values()]
                    ) / len(tot_breaths.keys())
                for var_name, var in zip(_trial_info, [patient, day, step, level]):
                    trial_details[protocol].loc[i, var_name] = var

 Processing patient MST001, protocol PS, day 24/12/2021, step 005 (12 cmH2O)
 Processing patient MST001, protocol PS, day 24/12/2021, step 004 (15 cmH2O)
 Processing patient MST001, protocol PS, day 24/12/2021, step 003 (18 cmH2O)
 Processing patient MST001, protocol PS, day 24/12/2021, step 002 (21 cmH2O)
 Processing patient MST001, protocol PEEP, day 24/12/2021, step 006 (3 cmH2O)
 Processing patient MST001, protocol PEEP, day 24/12/2021, step 007 (5 cmH2O)
 Processing patient MST001, protocol PEEP, day 24/12/2021, step 008 (7 cmH2O)
 Processing patient MST001, protocol PEEP, day 24/12/2021, step 009 (9 cmH2O)
 Processing patient MST001, protocol PS, day 03/01/2022, step 002 (3 cmH2O)
 Processing patient MST001, protocol PS, day 03/01/2022, step 003 (6 cmH2O)
 Processing patient MST001, protocol PS, day 03/01/2022, step 004 (9 cmH2O)
 Processing patient MST001, protocol PS, day 03/01/2022, step 005 (12 cmH2O)
 Processing patient MST001, protocol PEEP, day 03/01/2022, step 006 (3 cmH2O)
 Processing patient MST001, protocol PEEP, day 03/01/2022, step 007 (5 cmH2O)
 Processing patient MST001, protocol PEEP, day 03/01/2022, step 008 (7 cmH2O)
 Processing patient MST001, protocol PEEP, day 03/01/2022, step 009 (9 cmH2O)
 Processing patient MST001, protocol PS, day 31/12/2021, step 001 (3 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST001\PS\31_12_2021\3cmH2O.json does not exist, skipping.
 Processing patient MST001, protocol PS, day 31/12/2021, step 002 (6 cmH2O)
 Processing patient MST001, protocol PS, day 31/12/2021, step 003 (9 cmH2O)
 Processing patient MST001, protocol PS, day 31/12/2021, step 004 (12 cmH2O)
 Processing patient MST001, protocol PEEP, day 31/12/2021, step 005 (3 cmH2O)
 Processing patient MST001, protocol PEEP, day 31/12/2021, step 006 (5 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST001\PEEP\31_12_2021\5cmH2O.json does not exist, skipping.
 Processing patient MST001, protocol PEEP, day 31/12/2021, step 007 (7 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST001\PEEP\31_12_2021\7cmH2O.json does not exist, skipping.
 Processing patient MST001, protocol PEEP, day 31/12/2021, step 008 (9 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST001\PEEP\31_12_2021\9cmH2O.json does not exist, skipping.
 Processing patient MST001, protocol PS, day 29/12/2021, step 005 (3 cmH2O)
 Processing patient MST001, protocol PS, day 29/12/2021, step 004 (6 cmH2O)
 Processing patient MST001, protocol PS, day 29/12/2021, step 003 (9 cmH2O)
 Processing patient MST001, protocol PS, day 29/12/2021, step 002 (12 cmH2O)
 Processing patient MST001, protocol PEEP, day 29/12/2021, step 006 (3 cmH2O)
 Processing patient MST001, protocol PEEP, day 29/12/2021, step 007 (5 cmH2O)
 Processing patient MST001, protocol PEEP, day 29/12/2021, step 008 (7 cmH2O)
 Processing patient MST001, protocol PEEP, day 29/12/2021, step 009 (9 cmH2O)
 Processing patient MST001, protocol PS, day 27/12/2021, step 005 (3 cmH2O)
 Processing patient MST001, protocol PS, day 27/12/2021, step 004 (6 cmH2O)
 Processing patient MST001, protocol PS, day 27/12/2021, step 003 (9 cmH2O)
 Processing patient MST001, protocol PS, day 27/12/2021, step 002 (12 cmH2O)
 Processing patient MST001, protocol PEEP, day 27/12/2021, step 007 (3 cmH2O)
 Processing patient MST001, protocol PEEP, day 27/12/2021, step 008 (5 cmH2O)
 Processing patient MST001, protocol PEEP, day 27/12/2021, step 001 (7 cmH2O)
 Processing patient MST001, protocol PEEP, day 27/12/2021, step 011 (9 cmH2O)
 Processing patient MST002, protocol PS, day 07/01/2022, step 005 (6 cmH2O)
 Processing patient MST002, protocol PS, day 07/01/2022, step 004 (9 cmH2O)
 Processing patient MST002, protocol PS, day 07/01/2022, step 003 (12 cmH2O)
 Processing patient MST002, protocol PS, day 07/01/2022, step 002 (15 cmH2O)
 Processing patient MST002, protocol PEEP, day 07/01/2022, step 006 (7 cmH2O)
 Processing patient MST002, protocol PEEP, day 07/01/2022, step 007 (9 cmH2O)
 Processing patient MST002, protocol PEEP, day 07/01/2022, step 008 (11 cmH2O)
 Processing patient MST002, protocol PEEP, day 07/01/2022, step 009 (13 cmH2O)
 Processing patient MST002, protocol PS, day 10/01/2022, step 004 (3 cmH2O)
 Processing patient MST002, protocol PS, day 10/01/2022, step 003 (6 cmH2O)
 Processing patient MST002, protocol PS, day 10/01/2022, step 002 (9 cmH2O)
 Processing patient MST002, protocol PS, day 10/01/2022, step 001 (12 cmH2O)
 Processing patient MST002, protocol PEEP, day 10/01/2022, step 005 (3 cmH2O)
 Processing patient MST002, protocol PEEP, day 10/01/2022, step 006 (5 cmH2O)
 Processing patient MST002, protocol PEEP, day 10/01/2022, step 007 (7 cmH2O)
 Processing patient MST002, protocol PEEP, day 10/01/2022, step 008 (9 cmH2O)
 Processing patient MST003, protocol PS, day 28/01/2022, step 005 (9 cmH2O)
 Processing patient MST003, protocol PS, day 28/01/2022, step 004 (12 cmH2O)
 Processing patient MST003, protocol PS, day 28/01/2022, step 003 (15 cmH2O)
 Processing patient MST003, protocol PS, day 28/01/2022, step 002 (18 cmH2O)
 Processing patient MST003, protocol PEEP, day 28/01/2022, step 006 (3 cmH2O)
 Processing patient MST003, protocol PEEP, day 28/01/2022, step 007 (5 cmH2O)
 Processing patient MST003, protocol PEEP, day 28/01/2022, step 008 (7 cmH2O)
 Processing patient MST003, protocol PEEP, day 28/01/2022, step 009 (9 cmH2O)
 Processing patient MST003, protocol PS, day 02/02/2022, step 005 (3 cmH2O)
 Processing patient MST003, protocol PS, day 02/02/2022, step 004 (6 cmH2O)
 Processing patient MST003, protocol PS, day 02/02/2022, step 003 (9 cmH2O)
 Processing patient MST003, protocol PS, day 02/02/2022, step 002 (12 cmH2O)
 Processing patient MST003, protocol PEEP, day 02/02/2022, step 006 (5 cmH2O)
 Processing patient MST003, protocol PEEP, day 02/02/2022, step 007 (7 cmH2O)
 Processing patient MST003, protocol PEEP, day 02/02/2022, step 008 (9 cmH2O)
 Processing patient MST003, protocol PEEP, day 02/02/2022, step 009 (11 cmH2O)
 Processing patient MST003, protocol PS, day 31/01/2022, step 005 (9 cmH2O)
 Processing patient MST003, protocol PS, day 31/01/2022, step 004 (12 cmH2O)
 Processing patient MST003, protocol PS, day 31/01/2022, step 003 (15 cmH2O)
 Processing patient MST003, protocol PS, day 31/01/2022, step 002 (18 cmH2O)
 Processing patient MST003, protocol PEEP, day 31/01/2022, step 006 (3 cmH2O)
 Processing patient MST003, protocol PEEP, day 31/01/2022, step 007 (5 cmH2O)
 Processing patient MST003, protocol PEEP, day 31/01/2022, step 008 (7 cmH2O)
 Processing patient MST003, protocol PEEP, day 31/01/2022, step 009 (9 cmH2O)
 Processing patient MST003, protocol PS, day 26/01/2022, step 005 (6 cmH2O)
 Processing patient MST003, protocol PS, day 26/01/2022, step 004 (9 cmH2O)
 Processing patient MST003, protocol PS, day 26/01/2022, step 003 (12 cmH2O)
 Processing patient MST003, protocol PS, day 26/01/2022, step 002 (15 cmH2O)
 Processing patient MST003, protocol PEEP, day 26/01/2022, step 006 (3 cmH2O)
 Processing patient MST003, protocol PEEP, day 26/01/2022, step 007 (5 cmH2O)
 Processing patient MST003, protocol PEEP, day 26/01/2022, step 008 (7 cmH2O)
 Processing patient MST003, protocol PEEP, day 26/01/2022, step 009 (9 cmH2O)
 Processing patient MST004, protocol PS, day 02/02/2022, step 005 (3 cmH2O)
 Processing patient MST004, protocol PS, day 02/02/2022, step 004 (6 cmH2O)
 Processing patient MST004, protocol PS, day 02/02/2022, step 003 (9 cmH2O)
 Processing patient MST004, protocol PS, day 02/02/2022, step 002 (12 cmH2O)
 Processing patient MST004, protocol PEEP, day 02/02/2022, step 006 (5 cmH2O)
 Processing patient MST004, protocol PEEP, day 02/02/2022, step 007 (7 cmH2O)
 Processing patient MST004, protocol PEEP, day 02/02/2022, step 008 (9 cmH2O)
 Processing patient MST004, protocol PEEP, day 02/02/2022, step 009 (11 cmH2O)
 Processing patient MST004, protocol PS, day 07/02/2022, step 005 (3 cmH2O)
 Processing patient MST004, protocol PS, day 07/02/2022, step 004 (6 cmH2O)
 Processing patient MST004, protocol PS, day 07/02/2022, step 003 (9 cmH2O)
 Processing patient MST004, protocol PS, day 07/02/2022, step 002 (12 cmH2O)
 Processing patient MST004, protocol PEEP, day 07/02/2022, step 006 (3 cmH2O)
 Processing patient MST004, protocol PEEP, day 07/02/2022, step 007 (5 cmH2O)
 Processing patient MST004, protocol PEEP, day 07/02/2022, step 008 (7 cmH2O)
 Processing patient MST004, protocol PEEP, day 07/02/2022, step 009 (9 cmH2O)
 Processing patient MST004, protocol PS, day 28/01/2022, step 005 (9 cmH2O)
 Processing patient MST004, protocol PS, day 28/01/2022, step 004 (12 cmH2O)
 Processing patient MST004, protocol PS, day 28/01/2022, step 003 (15 cmH2O)
 Processing patient MST004, protocol PS, day 28/01/2022, step 002 (18 cmH2O)
 Processing patient MST004, protocol PEEP, day 28/01/2022, step 006 (5 cmH2O)
 Processing patient MST004, protocol PEEP, day 28/01/2022, step 007 (7 cmH2O)
 Processing patient MST004, protocol PEEP, day 28/01/2022, step 008 (9 cmH2O)
 Processing patient MST004, protocol PEEP, day 28/01/2022, step 009 (11 cmH2O)
 Processing patient MST004, protocol PS, day 04/02/2022, step 005 (3 cmH2O)
 Processing patient MST004, protocol PS, day 04/02/2022, step 004 (6 cmH2O)
 Processing patient MST004, protocol PS, day 04/02/2022, step 003 (9 cmH2O)
 Processing patient MST004, protocol PS, day 04/02/2022, step 002 (12 cmH2O)
 Processing patient MST004, protocol PEEP, day 04/02/2022, step 006 (5 cmH2O)
 Processing patient MST004, protocol PEEP, day 04/02/2022, step 007 (7 cmH2O)
 Processing patient MST004, protocol PEEP, day 04/02/2022, step 008 (9 cmH2O)
 Processing patient MST004, protocol PEEP, day 04/02/2022, step 009 (11 cmH2O)
 Processing patient MST005, protocol PS, day 28/02/2022, step 005 (3 cmH2O)
 Processing patient MST005, protocol PS, day 28/02/2022, step 004 (6 cmH2O)
 Processing patient MST005, protocol PS, day 28/02/2022, step 003 (9 cmH2O)
 Processing patient MST005, protocol PS, day 28/02/2022, step 002 (12 cmH2O)
 Processing patient MST005, protocol PEEP, day 28/02/2022, step 006 (7 cmH2O)
 Processing patient MST005, protocol PEEP, day 28/02/2022, step 007 (9 cmH2O)
 Processing patient MST005, protocol PEEP, day 28/02/2022, step 008 (11 cmH2O)
 Processing patient MST005, protocol PEEP, day 28/02/2022, step 009 (13 cmH2O)
 Processing patient MST006, protocol PS, day 18/03/2022, step 005 (3 cmH2O)
 Processing patient MST006, protocol PS, day 18/03/2022, step 004 (6 cmH2O)
 Processing patient MST006, protocol PS, day 18/03/2022, step 003 (9 cmH2O)
 Processing patient MST006, protocol PS, day 18/03/2022, step 002 (12 cmH2O)
 Processing patient MST006, protocol PEEP, day 18/03/2022, step 006 (7 cmH2O)
 Processing patient MST006, protocol PEEP, day 18/03/2022, step 007 (9 cmH2O)
 Processing patient MST006, protocol PEEP, day 18/03/2022, step 008 (11 cmH2O)
 Processing patient MST006, protocol PEEP, day 18/03/2022, step 009 (13 cmH2O)
 Processing patient MST007, protocol PS, day 18/03/2022, step 005 (3 cmH2O)
 Processing patient MST007, protocol PS, day 18/03/2022, step 004 (6 cmH2O)
 Processing patient MST007, protocol PS, day 18/03/2022, step 003 (9 cmH2O)
 Processing patient MST007, protocol PS, day 18/03/2022, step 002 (12 cmH2O)
 Processing patient MST007, protocol PEEP, day 18/03/2022, step 006 (3 cmH2O)
 Processing patient MST007, protocol PEEP, day 18/03/2022, step 007 (5 cmH2O)
 Processing patient MST007, protocol PEEP, day 18/03/2022, step 008 (7 cmH2O)
 Processing patient MST007, protocol PEEP, day 18/03/2022, step 009 (9 cmH2O)
 Processing patient MST007, protocol PS, day 11/03/2022, step 005 (6 cmH2O)
 Processing patient MST007, protocol PS, day 11/03/2022, step 004 (9 cmH2O)
 Processing patient MST007, protocol PS, day 11/03/2022, step 003 (12 cmH2O)
 Processing patient MST007, protocol PS, day 11/03/2022, step 002 (15 cmH2O)
 Processing patient MST007, protocol PEEP, day 11/03/2022, step 006 (3 cmH2O)
 Processing patient MST007, protocol PEEP, day 11/03/2022, step 007 (5 cmH2O)
 Processing patient MST007, protocol PEEP, day 11/03/2022, step 008 (7 cmH2O)
 Processing patient MST007, protocol PEEP, day 11/03/2022, step 009 (9 cmH2O)
 Processing patient MST007, protocol PS, day 14/03/2022, step 005 (6 cmH2O)
 Processing patient MST007, protocol PS, day 14/03/2022, step 004 (9 cmH2O)
 Processing patient MST007, protocol PS, day 14/03/2022, step 003 (12 cmH2O)
 Processing patient MST007, protocol PS, day 14/03/2022, step 002 (15 cmH2O)
 Processing patient MST007, protocol PEEP, day 14/03/2022, step 006 (3 cmH2O)
 Processing patient MST007, protocol PEEP, day 14/03/2022, step 007 (5 cmH2O)
 Processing patient MST007, protocol PEEP, day 14/03/2022, step 008 (7 cmH2O)
 Processing patient MST007, protocol PEEP, day 14/03/2022, step 009 (9 cmH2O)
 Processing patient MST008, protocol PS, day 25/03/2022, step 005 (6 cmH2O)
 Processing patient MST008, protocol PS, day 25/03/2022, step 004 (9 cmH2O)
 Processing patient MST008, protocol PS, day 25/03/2022, step 003 (12 cmH2O)
 Processing patient MST008, protocol PS, day 25/03/2022, step 002 (15 cmH2O)
 Processing patient MST008, protocol PEEP, day 25/03/2022, step 006 (5 cmH2O)
 Processing patient MST008, protocol PEEP, day 25/03/2022, step 007 (7 cmH2O)
 Processing patient MST008, protocol PEEP, day 25/03/2022, step 008 (9 cmH2O)
 Processing patient MST008, protocol PEEP, day 25/03/2022, step 009 (11 cmH2O)
 Processing patient MST009, protocol PS, day 28/03/2022, step 005 (3 cmH2O)
 Processing patient MST009, protocol PS, day 28/03/2022, step 004 (6 cmH2O)
 Processing patient MST009, protocol PS, day 28/03/2022, step 003 (9 cmH2O)
 Processing patient MST009, protocol PS, day 28/03/2022, step 002 (12 cmH2O)
 Processing patient MST009, protocol PEEP, day 28/03/2022, step 006 (7 cmH2O)
 Processing patient MST009, protocol PEEP, day 28/03/2022, step 007 (9 cmH2O)
 Processing patient MST009, protocol PEEP, day 28/03/2022, step 008 (11 cmH2O)
 Processing patient MST009, protocol PEEP, day 28/03/2022, step 009 (13 cmH2O)
 Processing patient MST009, protocol PS, day 30/03/2022, step 005 (6 cmH2O)
 Processing patient MST009, protocol PS, day 30/03/2022, step 004 (9 cmH2O)
 Processing patient MST009, protocol PS, day 30/03/2022, step 003 (12 cmH2O)
 Processing patient MST009, protocol PS, day 30/03/2022, step 002 (15 cmH2O)
 Processing patient MST009, protocol PEEP, day 30/03/2022, step 006 (5 cmH2O)
 Processing patient MST009, protocol PEEP, day 30/03/2022, step 007 (7 cmH2O)
 Processing patient MST009, protocol PEEP, day 30/03/2022, step 008 (9 cmH2O)
 Processing patient MST009, protocol PEEP, day 30/03/2022, step 009 (11 cmH2O)
 Processing patient MST010, protocol PS, day 25/04/2022, step 005 (9 cmH2O)
 Processing patient MST010, protocol PS, day 25/04/2022, step 004 (12 cmH2O)
 Processing patient MST010, protocol PS, day 25/04/2022, step 003 (15 cmH2O)
 Processing patient MST010, protocol PS, day 25/04/2022, step 002 (18 cmH2O)
 Processing patient MST010, protocol PEEP, day 25/04/2022, step 006 (7 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST010\PEEP\25_04_2022\7cmH2O.json does not exist, skipping.
 Processing patient MST010, protocol PEEP, day 25/04/2022, step 007 (9 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST010\PEEP\25_04_2022\9cmH2O.json does not exist, skipping.
 Processing patient MST010, protocol PEEP, day 25/04/2022, step 008 (11 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST010\PEEP\25_04_2022\11cmH2O.json does not exist, skipping.
 Processing patient MST010, protocol PEEP, day 25/04/2022, step 009 (13 cmH2O)
 Processing patient MST010, protocol PS, day 29/04/2022, step 005 (3 cmH2O)
 Processing patient MST010, protocol PS, day 29/04/2022, step 004 (6 cmH2O)
 Processing patient MST010, protocol PS, day 29/04/2022, step 003 (9 cmH2O)
 Processing patient MST010, protocol PS, day 29/04/2022, step 002 (12 cmH2O)
 Processing patient MST010, protocol PEEP, day 29/04/2022, step 006 (5 cmH2O)
 Processing patient MST010, protocol PEEP, day 29/04/2022, step 007 (7 cmH2O)
 Processing patient MST010, protocol PEEP, day 29/04/2022, step 008 (9 cmH2O)
 Processing patient MST010, protocol PEEP, day 29/04/2022, step 009 (11 cmH2O)
 Processing patient MST011, protocol PS, day 30/05/2022, step 005 (3 cmH2O)
 Processing patient MST011, protocol PS, day 30/05/2022, step 004 (6 cmH2O)
 Processing patient MST011, protocol PS, day 30/05/2022, step 003 (9 cmH2O)
 Processing patient MST011, protocol PS, day 30/05/2022, step 002 (12 cmH2O)
 Processing patient MST011, protocol PEEP, day 30/05/2022, step 006 (7 cmH2O)
 Processing patient MST011, protocol PEEP, day 30/05/2022, step 007 (9 cmH2O)
 Processing patient MST011, protocol PEEP, day 30/05/2022, step 008 (11 cmH2O)
 Processing patient MST011, protocol PEEP, day 30/05/2022, step 009 (13 cmH2O)
 Processing patient MST012, protocol PS, day 01/08/2022, step 005 (3 cmH2O)
 Processing patient MST012, protocol PS, day 01/08/2022, step 004 (6 cmH2O)
 Processing patient MST012, protocol PS, day 01/08/2022, step 003 (9 cmH2O)
 Processing patient MST012, protocol PS, day 01/08/2022, step 002 (12 cmH2O)
 Processing patient MST012, protocol PEEP, day 01/08/2022, step 006 (5 cmH2O)
 Processing patient MST012, protocol PEEP, day 01/08/2022, step 007 (7 cmH2O)
 Processing patient MST012, protocol PEEP, day 01/08/2022, step 008 (9 cmH2O)
 Processing patient MST012, protocol PEEP, day 01/08/2022, step 009 (11 cmH2O)
 Processing patient MST012, protocol PS, day 29/07/2022, step 005 (3 cmH2O)
 Processing patient MST012, protocol PS, day 29/07/2022, step 004 (6 cmH2O)
 Processing patient MST012, protocol PS, day 29/07/2022, step 003 (9 cmH2O)
 Processing patient MST012, protocol PS, day 29/07/2022, step 002 (12 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST012\PS\29_07_2022\12cmH2O.json does not exist, skipping.
 Processing patient MST012, protocol PEEP, day 29/07/2022, step 006 (5 cmH2O)
 Processing patient MST012, protocol PEEP, day 29/07/2022, step 007 (7 cmH2O)
 Processing patient MST012, protocol PEEP, day 29/07/2022, step 008 (9 cmH2O)
 Processing patient MST012, protocol PEEP, day 29/07/2022, step 009 (11 cmH2O)
 Processing patient MST012, protocol PS, day 27/07/2022, step 005 (3 cmH2O)
 Processing patient MST012, protocol PS, day 27/07/2022, step 004 (6 cmH2O)
 Processing patient MST012, protocol PS, day 27/07/2022, step 003 (9 cmH2O)
 >>>>> File C:\Users\ManinettiC\Documents\TOPSPIN_linked_legacy\MST012\PS\27_07_2022\9cmH2O.json does not exist, skipping.
 Processing patient MST012, protocol PS, day 27/07/2022, step 002 (12 cmH2O)
 Processing patient MST012, protocol PEEP, day 27/07/2022, step 006 (7 cmH2O)
 Processing patient MST012, protocol PEEP, day 27/07/2022, step 007 (9 cmH2O)
 Processing patient MST012, protocol PEEP, day 27/07/2022, step 008 (11 cmH2O)
 Processing patient MST012, protocol PEEP, day 27/07/2022, step 009 (13 cmH2O)
 Processing patient MST013, protocol PS, day 21/09/2022, step 005 (9 cmH2O)
 Processing patient MST013, protocol PS, day 21/09/2022, step 004 (12 cmH2O)
 Processing patient MST013, protocol PS, day 21/09/2022, step 003 (15 cmH2O)
 Processing patient MST013, protocol PS, day 21/09/2022, step 002 (18 cmH2O)
 Processing patient MST013, protocol PEEP, day 21/09/2022, step 006 (7 cmH2O)
 Processing patient MST013, protocol PEEP, day 21/09/2022, step 007 (9 cmH2O)
 Processing patient MST013, protocol PEEP, day 21/09/2022, step 008 (11 cmH2O)
 Processing patient MST013, protocol PEEP, day 21/09/2022, step 009 (13 cmH2O)
 Processing patient MST014, protocol PS, day 03/10/2022, step 005 (3 cmH2O)
 Processing patient MST014, protocol PS, day 03/10/2022, step 004 (6 cmH2O)
 Processing patient MST014, protocol PS, day 03/10/2022, step 003 (9 cmH2O)
 Processing patient MST014, protocol PS, day 03/10/2022, step 002 (12 cmH2O)

In [ ]:
_index_ps = pd.MultiIndex.from_frame(
    trial_details["PS"][["patient", "day", "level"]],
    names=["patient", "day", "PS_level"],
)
ps_details = pd.DataFrame(trial_details["PS"].iloc[:, 4:])
ps_details.set_index(_index_ps, inplace=True)
# ps_details
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
#     print(ps_details)

_index_valid_ps = _index_ps.droplevel("PS_level").drop_duplicates()
_valid_cols = [col for col in ps_details.columns if "percentage" in col]
ps_details_valid = pd.DataFrame(
    columns=[col.replace("_percentage", "") for col in _valid_cols],
    index=_index_valid_ps,
)
for idx in _index_valid_ps:
    ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()

print(ps_details_valid)

print("total valid trials: ", ps_details_valid.sum())

                   valid_vent valid_EMGdi valid_EMGic valid_linked_breaths
patient day
MST001  24/12/2021       True        True        True                False
        03/01/2022       True        True       False                False
        31/12/2021       True        True       False                False
        29/12/2021       True        True        True                False
        27/12/2021       True        True        True                False
MST002  07/01/2022       True       False       False                False
        10/01/2022       True       False       False                False
MST003  28/01/2022       True        True        True                False
        02/02/2022       True        True        True                False
        31/01/2022       True        True        True                False
        26/01/2022       True        True        True                False
MST004  02/02/2022       True        True        True                False
        07/02/2022       True        True        True                False
        28/01/2022       True        True        True                False
        04/02/2022       True        True        True                False
MST005  28/02/2022       True       False        True                False
MST006  18/03/2022       True       False        True                False
MST007  18/03/2022       True       False       False                False
        11/03/2022       True       False       False                False
        14/03/2022       True       False       False                False
MST008  25/03/2022       True       False       False                False
MST009  28/03/2022       True       False       False                False
        30/03/2022       True       False       False                False
MST010  25/04/2022       True       False        True                False
        29/04/2022       True        True        True                False
MST011  30/05/2022       True        True       False                False
MST012  01/08/2022       True       False       False                False
        29/07/2022       True        True       False                False
        27/07/2022       True        True       False                False
MST013  21/09/2022       True        True       False                False
MST014  03/10/2022       True        True       False                False
MST015  24/10/2022       True       False       False                False
        28/10/2022       True       False        True                False
MST016  28/10/2022       True       False       False                False
MST017  30/11/2022       True        True       False                False
        02/12/2022       True       False        True                False
        05/12/2022       True        True        True                False
        25/11/2022       True       False       False                False
        07/12/2022       True       False        True                False
        28/11/2022       True       False       False                False
        09/12/2022       True        True        True                False
total valid trials:  valid_vent              41
valid_EMGdi             22
valid_EMGic             20
valid_linked_breaths     0
dtype: object

C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()
C:\Users\ManinettiC\AppData\Local\Temp\ipykernel_40620\1160170857.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.
  ps_details_valid.loc[idx][:] = (ps_details.loc[idx][_valid_cols] > 10).all()

In [ ]:
_index_peep = pd.MultiIndex.from_frame(
    trial_details["PEEP"][["patient", "day", "level"]],
    names=["patient", "day", "PEEP_level"],
)
peep_details = pd.DataFrame(trial_details["PEEP"].iloc[:, 4:])
peep_details.set_index(_index_peep, inplace=True)
peep_details
with pd.option_context(
    "display.max_rows", None, "display.max_columns", None
):  # more options can be specified also
    print(peep_details)

                              valid_manoeuvers_vent valid_manoeuvers_EMGdi  \
patient day        PEEP_level
MST001  24/12/2021 3                              4                      3
                   5                              3                      3
                   7                              3                      2
                   9                              3                      3
        03/01/2022 3                              1                      3
                   5                              3                      3
                   7                              2                      1
                   9                              3                      3
        31/12/2021 3                              0                      1
        29/12/2021 3                              1                      0
                   5                              2                      0
                   7                              3                      0
                   9                              1                      2
        27/12/2021 3                              3                      1
                   5                              3                      0
                   7                              1                      3
                   9                              3                      0
MST002  07/01/2022 7                              1                      0
                   9                              2                      2
                   11                             2                      0
                   13                             0                      0
        10/01/2022 3                              1                      0
                   5                              1                      0
                   7                              0                      0
                   9                              0                      0
MST003  28/01/2022 3                              1                      1
                   5                              2                      1
                   7                              3                      3
                   9                              2                      2
        02/02/2022 5                              2                      1
                   7                              3                      3
                   9                              3                      3
                   11                             2                      1
        31/01/2022 3                              0                      0
                   5                              3                      3
                   7                              1                      2
                   9                              1                      0
        26/01/2022 3                              2                      3
                   5                              3                      3
                   7                              1                      3
                   9                              2                      2
MST004  02/02/2022 5                              3                      3
                   7                              3                      3
                   9                              0                      3
                   11                             0                      3
        07/02/2022 3                              3                      3
                   5                              3                      3
                   7                              2                      3
                   9                              1                      3
        28/01/2022 5                              0                      3
                   7                              0                      3
                   9                              0                      1
                   11                             1                      2
        04/02/2022 5                              1                      3
                   7                              1                      3
                   9                              0                      3
                   11                             0                      1
MST005  28/02/2022 7                              2                      1
                   9                              0                      0
                   11                             0                      0
                   13                             0                      0
MST006  18/03/2022 7                              0                      0
                   9                              0                      0
                   11                             0                      0
                   13                             1                      0
MST007  18/03/2022 3                              2                      2
                   5                              1                      0
                   7                              0                      0
                   9                              0                      0
        11/03/2022 3                              2                      0
                   5                              1                      0
                   7                              2                      0
                   9                              3                      0
        14/03/2022 3                              2                      0
                   5                              2                      0
                   7                              2                      0
                   9                              0                      0
MST008  25/03/2022 5                              4                      1
                   7                              5                      0
                   9                              4                      0
                   11                             2                      1
MST009  28/03/2022 7                              0                      0
                   9                              1                      0
                   11                             0                      0
                   13                             1                      0
        30/03/2022 5                              2                      2
                   7                              1                      0
                   9                              1                      0
                   11                             1                      0
MST010  25/04/2022 13                             0                      0
        29/04/2022 5                              2                      0
                   7                              0                      1
                   9                              1                      0
                   11                             0                      0
MST011  30/05/2022 7                              2                      2
                   9                              1                      3
                   11                             2                      2
                   13                             2                      2
MST012  01/08/2022 5                              1                      0
                   7                              0                      0
                   9                              0                      0
                   11                             0                      2
        29/07/2022 5                              0                      0
                   7                              0                      0
                   9                              1                      0
                   11                             1                      2
        27/07/2022 7                              3                      1
                   9                              1                      0
                   11                             1                      0
                   13                             1                      1
MST013  21/09/2022 7                              1                      2
                   9                              2                      2
                   11                             1                      2
                   13                             0                      0
MST014  03/10/2022 3                              1                      1
                   5                              1                      1
                   7                              3                      3
                   9                              2                      3
MST015  24/10/2022 7                              2                      0
                   9                              0                      0
                   11                             0                      0
                   13                             0                      0
                   7                              2                      0
        28/10/2022 5                              2                      1
                   7                              2                      0
                   9                              2                      0
                   11                             1                      0
MST016  28/10/2022 3                              0                      4
                   5                              0                      2
                   7                              0                      3
                   9                              0                      0
MST017  30/11/2022 7                              3                      3
                   9                              2                      3
                   11                             2                      3
                   13                             2                      2
        02/12/2022 3                              2                      0
                   5                              3                      1
                   7                              4                      4
                   9                              4                      0
        05/12/2022 3                              0                      0
                   5                              0                      0
                   7                              0                      0
                   9                              2                      1
        25/11/2022 7                              4                      0
                   9                              2                      0
                   11                             3                      0
                   13                             1                      0
        07/12/2022 3                              1                      0
                   5                              0                      0
                   7                              2                      1
                   9                              2                      0
        28/11/2022 7                              3                      0
                   9                              3                      0
                   11                             5                      0
                   13                             5                      1
        09/12/2022 3                              2                      1
                   5                              1                      0
                   7                              1                      0
                   9                              0                      0

                              valid_manoeuvers_EMGic  manoeuvers
patient day        PEEP_level
MST001  24/12/2021 3                               4         4.0
                   5                               3         3.0
                   7                               3         3.0
                   9                               3         3.0
        03/01/2022 3                               1         3.0
                   5                               2         3.0
                   7                               1         2.0
                   9                               3         3.0
        31/12/2021 3                               1         2.0
        29/12/2021 3                               0         2.0
                   5                               1         2.0
                   7                               0         3.0
                   9                               1         2.0
        27/12/2021 3                               3         3.0
                   5                               3         3.0
                   7                               5         5.0
                   9                               2         3.0
MST002  07/01/2022 7                               2         2.0
                   9                               3         3.0
                   11                              2         3.0
                   13                              2         2.0
        10/01/2022 3                               2         3.0
                   5                               3         3.0
                   7                               0         1.0
                   9                               0         1.0
MST003  28/01/2022 3                               2         3.0
                   5                               3         3.0
                   7                               3         3.0
                   9                               3         3.0
        02/02/2022 5                               0         2.0
                   7                               0         3.0
                   9                               0         3.0
                   11                              1         2.0
        31/01/2022 3                               2         2.0
                   5                               3         3.0
                   7                               2         2.0
                   9                               0         1.0
        26/01/2022 3                               3         3.0
                   5                               3         3.0
                   7                               2         3.0
                   9                               1         3.0
MST004  02/02/2022 5                               3         3.0
                   7                               3         3.0
                   9                               3         3.0
                   11                              3         3.0
        07/02/2022 3                               0         3.0
                   5                               0         3.0
                   7                               2         3.0
                   9                               2         3.0
        28/01/2022 5                               3         3.0
                   7                               3         3.0
                   9                               2         3.0
                   11                              3         3.0
        04/02/2022 5                               3         3.0
                   7                               3         3.0
                   9                               3         3.0
                   11                              2         2.0
MST005  28/02/2022 7                               2         3.0
                   9                               0         3.0
                   11                              0         1.0
                   13                              1         3.0
MST006  18/03/2022 7                               2         3.0
                   9                               3         3.0
                   11                              3         3.0
                   13                              2         3.0
MST007  18/03/2022 3                               1         3.0
                   5                               0         1.0
                   7                               0         1.0
                   9                               0         1.0
        11/03/2022 3                               2         2.0
                   5                               3         3.0
                   7                               3         3.0
                   9                               3         3.0
        14/03/2022 3                               2         2.0
                   5                               3         3.0
                   7                               1         3.0
                   9                               0         1.0
MST008  25/03/2022 5                               1         4.0
                   7                               1         6.0
                   9                               3         4.0
                   11                              1         3.0
MST009  28/03/2022 7                               2         2.0
                   9                               3         3.0
                   11                              0         1.0
                   13                              2         2.0
        30/03/2022 5                               2         2.0
                   7                               2         2.0
                   9                               0         1.0
                   11                              0         1.0
MST010  25/04/2022 13                              0         1.0
        29/04/2022 5                               2         3.0
                   7                               3         4.0
                   9                               3         3.0
                   11                              0         1.0
MST011  30/05/2022 7                               3         4.0
                   9                               0         3.0
                   11                              0         3.0
                   13                              2         2.0
MST012  01/08/2022 5                               2         2.0
                   7                               0         1.0
                   9                               0         1.0
                   11                              1         2.0
        29/07/2022 5                               0         1.0
                   7                               0         1.0
                   9                               0         1.0
                   11                              1         3.0
        27/07/2022 7                               3         4.0
                   9                               0         2.0
                   11                              0         1.0
                   13                              1         2.0
MST013  21/09/2022 7                               2         2.0
                   9                               1         3.0
                   11                              0         2.0
                   13                              0         1.0
MST014  03/10/2022 3                               0         2.0
                   5                               1         2.0
                   7                               1         3.0
                   9                               0         3.0
MST015  24/10/2022 7                               1         2.0
                   9                               0         1.0
                   11                              0         3.0

In [ ]:
# save the results
# now save the results to two json files (one for PEEP, one for PS)

for protocol, results in results_dict.items():
    _file = Path(r"C:\\Users\\ManinettiC\\Documents") / f"{protocol}_raw_results.json"
    with Path.open(_file, "w") as f:
        json.dump(results, f, indent=4, default=lambda df: df.to_json())

In [ ]:
# create a dataframe with the details of each trial (one for each protocol)

# PS protocol: valid trials have at least 10% valid neural breaths at each PS level

In [ ]:
print("Counts (valid/total)")

for protocol, dfs in results_dict.items():
    print(f"--- {protocol} ---")
    for measure, measure_dfs in dfs.items():
        print(f"--- {measure} ---")
        _total_df = measure_dfs["peak_df"]
        # print(f"{label}")
        valid = _total_df["valid"]
        breaths_tot = _total_df["start_idx"].count()
        breaths_valid = _total_df.loc[valid, "start_idx"].count()
        breaths_percent = (breaths_valid / breaths_tot) * 100
        _valid_df = (
            _total_df.loc[valid]
            .drop_duplicates(["patient", "day"])
            .groupby("patient")
            .size()
        )
        _total_df = (
            _total_df.drop_duplicates(["patient", "day"]).groupby("patient").size()
        )
        trials_valid = _valid_df.sum()
        trials_tot = _total_df.sum()
        trials_percent = (trials_valid / trials_tot) * 100
        patients_valid = _valid_df.count()
        patients_tot = _total_df.count()
        patients_percent = (patients_valid / patients_tot) * 100

        print(
            f"\tTotal breaths: {breaths_valid}/{breaths_tot} ({breaths_percent: .1f}%)"
        )
        print(f"\tTotal trials: {trials_valid}/{trials_tot} ({trials_percent: .1f}%)")
        print(
            f"\tTotal patients: {patients_valid}/{patients_tot} ({patients_percent: .1f}%)"
        )

Counts (valid/total)
--- PS ---
--- vent ---
	Total breaths: 68829/69347 ( 99.3%)
	Total trials: 41/41 ( 100.0%)
	Total patients: 17/17 ( 100.0%)
--- EMGdi ---
	Total breaths: 3224/61454 ( 5.2%)
	Total trials: 31/41 ( 75.6%)
	Total patients: 13/17 ( 76.5%)
--- EMGic ---
	Total breaths: 4065/69347 ( 5.9%)
	Total trials: 26/41 ( 63.4%)
	Total patients: 9/17 ( 52.9%)
--- PEEP ---
--- vent ---
	Total breaths: 227/391 ( 58.1%)
	Total trials: 38/41 ( 92.7%)
	Total patients: 16/17 ( 94.1%)
--- EMGdi ---
	Total breaths: 50/391 ( 12.8%)
	Total trials: 12/41 ( 29.3%)
	Total patients: 6/17 ( 35.3%)
--- EMGic ---
	Total breaths: 60/391 ( 15.3%)
	Total trials: 10/41 ( 24.4%)
	Total patients: 4/17 ( 23.5%)

In [ ]:
# show the count of valid protocols for each measure
quality_df = results_dict["PEEP"]["EMGdi"]["quality_outcomes_df"]
quality_tests = quality_df.dtypes == bool
quality_stats = pd.DataFrame(
    index=quality_tests.index[quality_tests],
    columns=["total protocols", "valid_protocols", "invalid_protocols", "patients"],
)
for test in quality_tests.index[quality_tests]:
    _df = (
        quality_df.loc[quality_df[test]]
        # .drop_duplicates(["patient", "day", "step"])
        .groupby("patient")
        .size()
    )
    quality_stats.loc[test, "total protocols"] = quality_df.shape[0]
    quality_stats.loc[test, "valid_protocols"] = _df.sum()
    quality_stats.loc[test, "invalid_protocols"] = (
        quality_stats.loc[test, "total protocols"] - _df.sum()
    )
    quality_stats.loc[test, "patients"] = _df.nunique()
    # print(f"\t{test}: {_df.sum()} valid protocols, {_df.nunique()} patients")

quality_stats

                   total protocols valid_protocols invalid_protocols patients
baseline_detection             391             255               136        9
interpeak_distance             391             364                27       12
snr                            391             150               241        9
aub                            391             129               262       13
bell                           391             375                16       10
relative_aub                   391             390                 1       12
relative_etp                   391             383                 8       13

In [ ]:
patient = "MST001"
day = "24/12/2021"
protocol = "PEEP"
# level = 5
signals = ["vent", "EMGdi", "EMGic"]

baseline = 9 if protocol == "PEEP" else 12
print(step)
if protocol == "PS":
    columns = [
        var + "_" + signal for signal in ["EMGdi", "EMGic"] for var in ["ETP", "sEA"]
    ] + ["TV"]
elif protocol == "PEEP":
    columns = ["PTPocc_vent"] + [
        var + "_" + signal for signal in ["EMGdi", "EMGic"] for var in ["ETP"]
    ]

results = pd.DataFrame(columns=["patient", "day", "level"] + columns)
results_normalized = pd.DataFrame(columns=["patient", "day", "level"] + columns)

# _results = pd.DataFrame(columns = ["patient", "day", "level""])
for signal in signals:
    if protocol == "PS":
        measures = ["TV"] if signal == "vent" else ["ETP", "sEA"]
    elif protocol == "PEEP":
        measures = ["PTPocc"] if signal == "vent" else ["ETP"]
    _df = pd.DataFrame()
    _df = results_dict[protocol][signal]["peak_df"].copy()
    mean_bs = _df.query(
        f"patient == '{patient}' and day == '{day}' and level == {baseline}"
    )
    _selected = _df.query(f"patient == '{patient}' and day == '{day}'")
    results["level"] = _selected["level"]
    results_normalized["level"] = _selected["level"]

    _selected = _selected[["valid"] + measures]
    _selected.columns = [col + "_" + signal for col in _selected.columns]

    for measure in measures:
        meas_col_name = measure + "_" + signal
        _mean_bs = mean_bs[mean_bs["valid"]][measure].mean()
        # _std_bs = _df[(_df["patient"] == patient) & (_df["day"] == day) & (_df["level"] == baseline)][[measure]].std()
        # _std_bs = _std_bs.replace(0, 1)  # replace 0 std with NaN to avoid division by zero
        _selected[meas_col_name + "_normalized"] = _selected[meas_col_name].apply(
            lambda x: x / _mean_bs
        )
        results_normalized[meas_col_name] = _selected[meas_col_name + "_normalized"]
        results[meas_col_name] = _selected[meas_col_name]

results["patient"] = patient
results["day"] = day
results_normalized["patient"] = patient
results_normalized["day"] = day


if protocol == "PEEP":
    for measure in ["EMGdi", "EMGic"]:
        results_normalized[f"NME_{measure}"] = (
            results_normalized["PTPocc_vent"] / results_normalized[f"ETP_{measure}"]
        )
        results[f"NME_{measure}"] = results["PTPocc_vent"] / results[f"ETP_{measure}"]

display(results)
display(results_normalized)

009

,patient,day,level,PTPocc_vent,ETP_EMGdi,ETP_EMGic,NME_EMGdi,NME_EMGic
0,MST001,24/12/2021,3,6.151575,1.011590,7.961664,6.081096,0.772649
1,MST001,24/12/2021,3,6.288096,1.843908,7.920304,3.410200,0.793921
2,MST001,24/12/2021,3,7.216023,1.868812,8.860439,3.861288,0.814409
3,MST001,24/12/2021,3,6.714154,1.880686,9.696665,3.570056,0.692419
4,MST001,24/12/2021,5,7.816000,1.822360,10.902711,4.288944,0.716886
5,MST001,24/12/2021,5,6.951271,1.844896,8.596340,3.767839,0.808632
6,MST001,24/12/2021,5,6.612928,1.668423,7.563955,3.963579,0.874269
7,MST001,24/12/2021,7,7.765417,2.226424,11.764503,3.487844,0.660072
8,MST001,24/12/2021,7,7.123509,2.140628,9.831386,3.327765,0.724568
9,MST001,24/12/2021,7,7.020986,0.279947,9.882248,25.079659,0.710465
10,MST001,24/12/2021,9,7.336311,2.063408,10.821990,3.555435,0.677908
11,MST001,24/12/2021,9,7.320816,2.048119,11.944566,3.574409,0.612899
12,MST001,24/12/2021,9,6.977239,2.659555,11.344613,2.623461,0.615027

,patient,day,level,PTPocc_vent,ETP_EMGdi,ETP_EMGic,NME_EMGdi,NME_EMGic
0,MST001,24/12/2021,3,0.853028,0.448196,0.700210,1.903250,1.218246
1,MST001,24/12/2021,3,0.871959,0.816963,0.696573,1.067318,1.251785
2,MST001,24/12/2021,3,1.000633,0.827997,0.779256,1.208498,1.284089
3,MST001,24/12/2021,3,0.931040,0.833258,0.852800,1.117349,1.091745
4,MST001,24/12/2021,5,1.083831,0.807416,0.958869,1.342345,1.130323
5,MST001,24/12/2021,5,0.963921,0.817401,0.756029,1.179251,1.274979
6,MST001,24/12/2021,5,0.917003,0.739213,0.665233,1.240513,1.378470
7,MST001,24/12/2021,7,1.076817,0.986441,1.034661,1.091618,1.040743
8,MST001,24/12/2021,7,0.987805,0.948428,0.864648,1.041517,1.142435
9,MST001,24/12/2021,7,0.973588,0.124034,0.869121,7.849382,1.120198
10,MST001,24/12/2021,9,1.017314,0.914215,0.951770,1.112773,1.068865
11,MST001,24/12/2021,9,1.015165,0.907441,1.050497,1.118712,0.966366
12,MST001,24/12/2021,9,0.967522,1.178344,0.997733,0.821086,0.969720

In [ ]:
import importlib
import resurfemg

importlib.reload(resurfemg)
import resurfemg

importlib.reload(resurfemg.pipelines.multimodal)
from resurfemg.pipelines.multimodal import MultimodalDataGroup

level = 3
step = next(
    _step
    for _step, d in PS_dict[patient][day].items()
    if d["trial"] == protocol and d["cmH2O"] == level
)
plt.close("all")
record = PS_dict[patient][day][step]

mdg = MultimodalDataGroup(
    cast(
        "VentilatorDataGroup",
        ds.get_data(
            Poly5Reader(str(record["Ventilator"]), verbose=False),
            "Ventilator",
            verbose=False,
        ),
    ),
    cast(
        "EmgDataGroup",
        ds.get_data(
            Poly5Reader(str(record["EMG"]), verbose=False),
            "EMG",
            verbose=False,
        ),
    ),
)
mdg.set_labels()
mdg.process_emg()
mdg.get_emg_breaths(trial=protocol)
if protocol == "PEEP":
    mdg.process_ventilator_breaths(trial=protocol)
    mdg.link_breaths(trial=protocol)
    mdg.detect_emg_on_offsets(trial=protocol)
    mdg.calculate_ETP(trial=protocol)
    mdg.calculate_PTP()
    mdg.compute_quality_criteria(trial=protocol)
    peak_set_name, vent_idx = "Pocc", mdg.p_vent_idx
else:
    mdg.detect_emg_on_offsets(trial=protocol)
    mdg.calculate_ETP(trial=protocol)
    mdg.compute_quality_criteria(trial=protocol)
    mdg.process_ventilator_breaths(trial=protocol)
    mdg.link_breaths(trial=protocol)
    peak_set_name, vent_idx = "neural_breaths", mdg.v_vent_idx
mdg.calculate_peak_values(trial=protocol)
for df_name in ["peak_df", "quality_values_df", "quality_outcomes_df"]:
    _d_temp.setdefault("vent", {})[df_name] = getattr(
        mdg.vent_timeseries[vent_idx].peaks[peak_set_name], df_name
    )
    for idx in mdg.emg_idx:
        label = mdg.emg_timeseries.labels[idx]
        _d_temp.setdefault(label, {})[df_name] = getattr(
            mdg.emg_timeseries[label].peaks[peak_set_name], df_name
        )
mdg.plot_data(trial=protocol)

mdg.emg_timeseries[1].peaks["Pocc"].peak_df

c:\Users\ManinettiC\Documents\ReSurfEMG\resurfemg\data_connector\data_classes.py:1987: UserWarning: Peak set 'Pocc' not found in channel 0.
  warnings.warn(msg, UserWarning)
c:\Users\ManinettiC\Documents\ReSurfEMG\resurfemg\data_connector\data_classes.py:1987: UserWarning: Peak set 'Pocc' not found in channel 1.
  warnings.warn(msg, UserWarning)
c:\Users\ManinettiC\Documents\ReSurfEMG\resurfemg\data_connector\data_classes.py:1987: UserWarning: Peak set 'Pocc' not found in channel 2.
  warnings.warn(msg, UserWarning)

,peak_idx,start_idx,end_idx,valid,AUB,aub_y_ref,ETP,bell_y_min,bell_a,bell_b,bell_c
0,703158,703090,703270,True,0.049863,1.738269,0.158812,1.738269,1.863301,343.334497,0.166359
1,788945,788618,789033,True,0.121450,2.048654,0.965309,2.048654,5.063793,385.191854,0.249014

In [ ]:
pks = mdg.emg_timeseries[1].peaks["Pocc"].peak_df
display((pks["end_idx"] - pks["start_idx"]) / 2048)

0    0.945801
1    0.928711
2    0.679199
3    0.719238
dtype: float64

In [ ]:
self = mdg
plot_markers = True
if plot_markers is True:
    if protocol == "PS":
        markers = ["neural_breaths", "neural_breaths", "neural_breaths"]
    else:
        markers = ["Pocc", "Pocc", "Pocc"]
nrows = 3
ncols = 2
axes = plt.subplots(
    nrows=nrows, ncols=ncols, sharex=True, figsize=(ncols * 6, nrows * 2)
)[1]

axes_emg = axes[:, 0]
axes_vent = axes[:, 1]

self.emg_timeseries.plot_full(
    axes=axes_emg,
    baseline_bool=True,
)

self.vent_timeseries.plot_full(
    axes=axes_vent,
    baseline_bool=True,
)

if plot_markers is True:
    self.emg_timeseries.plot_markers(
        peak_set_name=markers,
        axes=np.transpose([axes_emg]),
        colors=["tab:red", "tab:green", "tab:green"],
    )
    self.vent_timeseries.plot_markers(
        peak_set_name=markers,
        axes=np.transpose([axes_vent]),
        colors=["tab:red", "tab:green", "tab:green"],
    )

axes_emg[0].set_title("EMG data")
axes_emg[-1].set_xlabel("t (s)")
axes_vent[0].set_title("Ventilator data")
axes_vent[-1].set_xlabel("t (s)")
plt.show()

c:\Users\ManinettiC\Documents\ReSurfEMG\resurfemg\data_connector\data_classes.py:1987: UserWarning: Peak set 'Pocc' not found in channel 0.
  warnings.warn(msg, UserWarning)
c:\Users\ManinettiC\Documents\ReSurfEMG\resurfemg\data_connector\data_classes.py:1987: UserWarning: Peak set 'Pocc' not found in channel 1.
  warnings.warn(msg, UserWarning)
c:\Users\ManinettiC\Documents\ReSurfEMG\resurfemg\data_connector\data_classes.py:1987: UserWarning: Peak set 'Pocc' not found in channel 2.
  warnings.warn(msg, UserWarning)

In [ ]:
_sel = _df[(_df["patient"] == patient) & (_df["day"] == day) & (_df["level"] == level)]
_sel = _sel[_sel["valid"] == True]

_sel["sum"] = _sel["AUB"] + _sel["ETP"] + _sel["aub_y_ref"]
_sel

In [ ]:
linked_breaths = {}

# PS - IMPORT THE LINKED BREATHS

In [39]:
import ast
_lb = json.load(open("C:\\Users\\ManinettiC\\Documents\\PS_raw_results.json"))
linked_breaths = {}
_lb = _lb['linked_breaths']
for df_name in ["peak_df", "quality_values_df", "quality_outcomes_df"]:
    df = pd.read_json(StringIO(_lb[df_name])).drop(columns="step")
    

    row_keys = ['patient', 'day', 'level']
    df = df.set_index(row_keys)

    def to_tuple(c):
        if isinstance(c, tuple):
            return c
        if isinstance(c, str) and c.startswith('('):
            return ast.literal_eval(c)      # "('di', 'ETP')" -> ('di', 'ETP')
        return ('meta', c)                  # leftover flat columns, e.g. 'step'

    df.columns = pd.MultiIndex.from_tuples([to_tuple(c) for c in df.columns])
    df = df.sort_index().sort_index(axis=1)
    linked_breaths[df_name] = df

del _lb

In [ ]:
show(linked_breaths['peak_df'], 100)

In [ ]:
import numpy as np
import pandas as pd

REF_LEVEL = 9            # level used as reference (match dtype of the 'level' index: 9 vs '9')
AGG = 'median'           # how to collapse multiple breaths at REF_LEVEL into one reference value
VALID_ONLY = False        # use only breaths with <signal>.valid == 1 to build the reference
SKIP = {'valid', 'peak_idx', 'start_idx', 'end_idx'}   # columns not normalized


def normalize_to_level(df, ref_level=REF_LEVEL, agg=AGG, valid_only=VALID_ONLY, skip=SKIP):
    """
    df: rows MultiIndex (patient, day, level), columns MultiIndex (signal, measure).
    Returns (normalized df, reference table indexed by (patient, day)).
    """
    measure_cols = [c for c in df.columns if c[1] not in skip]

    # Rows at the reference level, indexed by (patient, day)
    ref_rows = df.xs(ref_level, level='level')

    # One reference value per (patient, day) per measure
    refs = {}
    for col in measure_cols:
        s = ref_rows[col]
        valid_col = (col[0], 'valid')
        if valid_only and valid_col in df.columns:
            s = s[ref_rows[valid_col] == 1]
        refs[col] = s.groupby(level=['patient', 'day']).agg(agg)
    ref = pd.DataFrame(refs)
    ref.columns = pd.MultiIndex.from_tuples(ref.columns)

    # Broadcast the reference to every row of the same (patient, day)
    ref_aligned = ref.reindex(df.index.droplevel('level'))[measure_cols]

    out = df.copy()
    out[measure_cols] = df[measure_cols].to_numpy() / ref_aligned.to_numpy()
    out[measure_cols] = out[measure_cols].replace([np.inf, -np.inf], np.nan)
    return out, ref

## Create a normalized dataframe

In [77]:
linked_peaks = linked_breaths['peak_df']
baseline = 9

columns = {key: [col for col in linked_peaks[key].columns.tolist() if 'idx' not in col and col != 'valid'] for key in linked_peaks.columns.get_level_values(0).unique()}

linked_peaks_normalized = linked_peaks.copy().drop(columns=[(col[0], col[1]) for col in linked_peaks.columns if col[1] in ['valid', 'peak_idx', 'start_idx', 'end_idx']])
# results = pd.DataFrame(columns=["patient", "day", "level"] + columns)
# results_normalized = pd.DataFrame(columns=["patient", "day", "level"] + columns)
linked_peaks_normalized, _ = normalize_to_level(linked_peaks_normalized.sort_index())

## Plot the trends

In [82]:
import matplotlib.pyplot as plt
import pandas as pd


def plot_measure_3d(df, measure=('di', 'ETP'), patients=None, agg='median'):
    """
    df: rows MultiIndex (patient, day, level), columns MultiIndex (signal, measure).
    x: days since the patient's first recording day
    y: level
    z: measure, aggregated over breaths per (patient, day, level)
    """
    # Days since first record, computed from all rows (not only rows where this measure exists)
    idx = df.index.to_frame(index=False)[['patient', 'day']].drop_duplicates()
    idx['date'] = pd.to_datetime(idx['day'], format='%d/%m/%Y')
    idx['days_from_first'] = (idx['date'] - idx.groupby('patient')['date'].transform('min')).dt.days

    # Raw: one row per breath
    raw = (df[measure].dropna()
           .reset_index(name='value')
           .merge(idx[['patient', 'day', 'days_from_first']], on=['patient', 'day']))
    raw['level'] = pd.to_numeric(raw['level'])

    # Trend: one value per (patient, day, level)
    g = (raw.groupby(['patient', 'day', 'level', 'days_from_first'])['value']
         .agg(agg).reset_index())

    if patients is not None:
        raw = raw[raw['patient'].isin(patients)]
        g = g[g['patient'].isin(patients)]

    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(projection='3d')
    cmap = plt.get_cmap('tab20')

    for i, pat in enumerate(sorted(g['patient'].unique())):
        color = cmap(i % 20)

        # Individual breaths
        rp = raw[raw['patient'] == pat]
        ax.scatter(rp['days_from_first'], rp['level'], rp['value'],
                   color=color, s=2, alpha=0.15, depthshade=False)

        # Trendlines: aggregated value across levels, one line per day
        gp = g[g['patient'] == pat]
        for j, (_, gd) in enumerate(gp.groupby('days_from_first')):
            gd = gd.sort_values('level')
            ax.plot(gd['days_from_first'], gd['level'], gd['value'],
                    color=color, marker='o', ms=4, lw=2,
                    label=pat if j == 0 else None)

    ax.set_xlabel('Days from first record')
    ax.set_ylabel('Level (cmH2O)')
    ax.set_zlabel(f'{measure[0]} {measure[1]} ({agg})')
    ax.legend(loc='upper left', fontsize=7, ncol=2)
    plt.tight_layout()
    return fig, ax


if __name__ == '__main__':
    # fig, ax = plot_measure_3d(df_norm, measure=('di', 'ETP'))
    # fig, ax = plot_measure_3d(df_norm, measure=('vent', 'TV'), patients=['MST001', 'MST003'])
    plt.show()

In [91]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import ipywidgets as widgets


def prepare(df, measure):
    """Return (raw per-breath table, box statistics per (patient, day, level))."""
    # Days since first record, computed from all rows (not only rows where this measure exists)
    idx = df.index.to_frame(index=False)[['patient', 'day']].drop_duplicates()
    idx['date'] = pd.to_datetime(idx['day'], format='%d/%m/%Y')
    idx['days_from_first'] = (idx['date'] - idx.groupby('patient')['date'].transform('min')).dt.days

    raw = (df[measure].dropna()
           .reset_index(name='value')
           .merge(idx[['patient', 'day', 'days_from_first']], on=['patient', 'day']))
    raw['level'] = pd.to_numeric(raw['level'])

    def _box(v):
        q1, med, q3 = np.percentile(v, [25, 50, 75])
        iqr = q3 - q1
        inside = v[(v >= q1 - 1.5 * iqr) & (v <= q3 + 1.5 * iqr)]
        return pd.Series({'q1': q1, 'med': med, 'q3': q3,
                          'whislo': inside.min(), 'whishi': inside.max(), 'n': len(v)})

    stats = (raw.groupby(['patient', 'day', 'level', 'days_from_first'])['value']
             .apply(lambda s: _box(s.to_numpy())).unstack().reset_index())

    # Flag outliers for plotting
    raw = raw.merge(stats[['patient', 'day', 'level', 'whislo', 'whishi']],
                    on=['patient', 'day', 'level'])
    raw['outlier'] = (raw['value'] < raw['whislo']) | (raw['value'] > raw['whishi'])
    return raw, stats


def _draw_box(ax, x, y, s, color, wx, wy, alpha):
    """One 3D box: cuboid Q1–Q3, square at the median, vertical whiskers with caps."""
    ax.bar3d(x - wx / 2, y - wy / 2, s.q1, wx, wy, max(s.q3 - s.q1, 1e-12),
             color=color, alpha=alpha, shade=True, edgecolor=color, linewidth=0.3)
    # Median: square outline around the box at z = median
    xs = [x - wx / 2, x + wx / 2, x + wx / 2, x - wx / 2, x - wx / 2]
    ys = [y - wy / 2, y - wy / 2, y + wy / 2, y + wy / 2, y - wy / 2]
    ax.plot(xs, ys, [s.med] * 5, color='k', lw=1.2)
    # Whiskers + caps
    ax.plot([x, x], [y, y], [s.whislo, s.q1], color=color, lw=1)
    ax.plot([x, x], [y, y], [s.q3, s.whishi], color=color, lw=1)
    for z in (s.whislo, s.whishi):
        ax.plot([x - wx / 4, x + wx / 4], [y, y], [z, z], color=color, lw=1)


def plot_patients(raw, stats, patients, measure, box_width=(0.4, 0.8),
                  box_alpha=0.35, show_points='outliers', ax=None):
    """
    box_width: (days, cmH2O) footprint of each box.
    show_points: 'outliers', 'all', or None.
    """
    if ax is None:
        fig = plt.figure(figsize=(10, 7))
        ax = fig.add_subplot(projection='3d')
    cmap = plt.get_cmap('tab20')
    all_patients = sorted(stats['patient'].unique())
    wx, wy = box_width

    for pat in patients:
        k = all_patients.index(pat) % 20
        color = cmap(2 * k % 20 + (k >= 10))   # spread tab20 so neighbours differ

        for s in stats[stats['patient'] == pat].itertuples():
            _draw_box(ax, s.days_from_first, s.level, s, color, wx, wy, box_alpha)

        if show_points:
            rp = raw[raw['patient'] == pat]
            if show_points == 'outliers':
                rp = rp[rp['outlier']]
            ax.scatter(rp['days_from_first'], rp['level'], rp['value'],
                       color=color, s=3, alpha=0.3, depthshade=False)

        ax.plot([], [], color=color, lw=6, label=pat)   # legend handle

    ax.set_xlabel('Days from first record')
    ax.set_ylabel('Level (cmH2O)')
    ax.set_zlabel(f'{measure[0]} {measure[1]}')
    ax.set_title(f'{measure[0]} {measure[1]} — '
                 f'{", ".join(patients) if len(patients) < 4 else "all patients"}')
    ax.legend(loc='upper left', fontsize=7, ncol=2)
    return ax


def plot_measure_3d(df, measure=('di', 'ETP'), **kwargs):
    """Interactive: dropdown to pick a patient (or All). kwargs go to plot_patients."""
    raw, stats = prepare(df, measure)
    patients = sorted(stats['patient'].unique())

    def _draw(patient):
        sel = patients if patient == 'All' else [patient]
        plot_patients(raw, stats, sel, measure, **kwargs)
        plt.tight_layout()
        plt.show()

    widgets.interact(_draw, patient=widgets.Dropdown(options=['All'] + patients,
                                                     value=patients[0],
                                                     description='Patient'))


# In a notebook:
# plot_measure_3d(df_norm, measure=('di', 'ETP'))
# plot_measure_3d(df_norm, measure=('vent', 'TV'), show_points='all', box_width=(0.3, 0.6))

In [95]:
plot_measure_3d(linked_peaks_normalized, measure=('di', 'ETP'))

interactive(children=(Dropdown(description='Patient', index=1, options=('All', 'MST001', 'MST002', 'MST003', '…

In [96]:
plot_measure_3d(linked_peaks_normalized, measure=('ic', 'ETP'))

interactive(children=(Dropdown(description='Patient', index=1, options=('All', 'MST001', 'MST002', 'MST003', '…

In [85]:
ax = plt.gca()
ax.set_zlim(0, 200)

(0.0, 200.0)

# Process file (manual)

In [ ]:
# ensure the correct labels are set

vent_timeseries.v_vent_idx = next(
    i for i, s in enumerate(vent_timeseries.labels) if "V" in s
)
vent_timeseries.p_vent_idx = next(
    i for i, s in enumerate(vent_timeseries.labels) if "P" in s
)
vent_timeseries.f_idx = next(
    i for i, s in enumerate(vent_timeseries.labels) if "F" in s
)

emg_timeseries.labels = ["ECG", "EMGdi", "EMGic"]
for idx, label in enumerate(emg_timeseries.labels):
    emg_timeseries[idx].label = label

In [ ]:
# plot the imported data

plt.close("all")

nrows = 3
ncols = 2
axes = plt.subplots(
    nrows=nrows, ncols=ncols, sharex=True, figsize=(ncols * 6, nrows * 2)
)[1]

axes_emg = axes[:, 0]
axes_vent = axes[:, 1]

emg_timeseries.plot_full(
    axes=axes_emg,
)


vent_timeseries.plot_full(
    axes=axes_vent,
)


axes_emg[0].set_title("EMG data")
axes_emg[-1].set_xlabel("t (s)")
axes_vent[0].set_title("Ventilator data")
axes_vent[-1].set_xlabel("t (s)")
plt.show()

# 3. Processing of ventilator signals

## PEEP settings and moving baseline

In [ ]:
# compute PEEP
vent_timeseries.find_peep()
# compute moving baseline
vent_timeseries.baseline(
    channel_idxs=[vent_timeseries.p_vent_idx], signal_io=("raw", "baseline")
)

## Pocc peak detection and PTPocc calculation

In [ ]:
# detect occlusion pressure peaks
vent_timeseries.find_occluded_breaths()

# detectPocc on- and offset
vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].detect_on_offset(
    baseline=vent_timeseries[vent_timeseries.p_vent_idx]["baseline"],
    fs=vent_timeseries.fs,
)

# calculate PTPocc as the area between Paw and the moving baseline between the on- and offset of the Pocc peak
vent_timeseries[vent_timeseries.p_vent_idx].calculate_time_products(
    peak_set_name="Pocc",
    parameter_name="PTPocc",
    aub_reference_signal=vent_timeseries[vent_timeseries.p_vent_idx]["baseline"],
    include_aub=True,
)

In [ ]:
# vent_timeseries.find_ventilator_peaks()

for idx in [vent_timeseries.v_vent_idx, vent_timeseries.f_idx]:
    vent_timeseries.baseline(channel_idxs=[idx], signal_io=("raw", "baseline"))
    vent_timeseries.find_ventilator_peaks(
        channel_io=(idx, idx), peak_set_name="ventilator_breaths", overwrite=True
    )
    vent_timeseries[idx].link_peak_set(
        peak_set_name="ventilator_breaths",
        t_reference_peaks=vent_timeseries[vent_timeseries.p_vent_idx]
        .peaks["Pocc"]
        .peak_df["peak_idx"]
        .to_numpy()
        / vent_timeseries.param["fs"],
        linked_peak_set_name="Pocc",
    )
    vent_timeseries[idx].peaks["Pocc"].detect_on_offset(
        baseline=vent_timeseries[idx]["baseline"],
    )

    vent_timeseries[idx].calculate_time_products(
        peak_set_name="Pocc",
        parameter_name="PTPbreaths",
        aub_reference_signal=vent_timeseries[vent_timeseries.p_vent_idx]["baseline"],
        include_aub=True,
    )
    print(vent_timeseries.labels[idx], vent_timeseries[idx].peaks["Pocc"].peak_df)

## Pocc quality criteria

In [ ]:
for idx in [0, 1, 2]:
    print(vent_timeseries.labels[idx], vent_timeseries[idx].peaks["Pocc"])

# 4. Processing of sEMG signals

## QRS complex detection

In [ ]:
# filter the data
emg_timeseries.filter()

# get the indexes of the ecg and emg channels
emg_timeseries.ecg_idx = next(
    i for i, s in enumerate(emg_timeseries.labels) if "ECG" in s
)
emg_idx = [
    i for i in range(len(emg_timeseries.channels)) if i != emg_timeseries.ecg_idx
]

# Filter the ECG signal and detect the QRS complexes
emg_timeseries.get_ecg_peaks(name="ecg")

# Perform gating to remove the ECG artifacts from the EMG signals
emg_timeseries.gating(
    channel_idxs=emg_idx,
    ecg_peakset_name="ecg",
    gate_width_samples=int(0.1 * emg_timeseries.param["fs"]),
)

# compute the sEA envelope
emg_timeseries.envelope(
    channel_idxs=emg_idx,
    env_window=int(0.2 * emg_timeseries.param["fs"]),
    env_type="rms",
)

## Improved moving slopesum baseline

In [ ]:
# calculate the slopesum moving baseline
emg_timeseries.baseline(
    channel_idxs=emg_idx,
    base_method="slopesum_baseline",
    window_s=int(7.5 * emg_timeseries.param["fs"]),
    ma_window=int(0.5 * emg_timeseries.param["fs"]),
)

## Peak detection

In [ ]:
# detect the sEA peaks
emg_timeseries.detect_emg_breaths(
    channel_idxs=emg_idx,
    # min_peak_width_s=int(0.5 * emg_timeseries.param["fs"]),
    peak_set_name="emg_breaths",
)
# get the on and offsets as baseline crossing points
for idx in emg_idx:
    emg_timeseries[idx].peaks["emg_breaths"].detect_on_offset(
        baseline=emg_timeseries[idx]["baseline"],
        fs=emg_timeseries.fs,
        # method="slope_extrapolation",
    )
    emg_timeseries[idx].link_peak_set(
        peak_set_name="emg_breaths",
        t_reference_peaks=vent_timeseries[vent_timeseries.p_vent_idx]
        .peaks["Pocc"]
        .peak_df["peak_idx"]
        .to_numpy()
        / vent_timeseries.param["fs"],
        linked_peak_set_name="Pocc",
    )

In [ ]:
# link EMG peaks to the closest Pocc peaks
emg_timeseries.link_peak_set(
    channel_idxs=emg_idx,
    peak_set_name="emg_breaths",
    t_reference_peaks=np.asarray(
        vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].peak_df["peak_idx"]
    )
    / vent_timeseries.param["fs"],
    linked_peak_set_name="Pocc",
)

In [ ]:
# plot the detected Pocc peaks and the linked EMG peaks

n_peaks = len(
    emg_timeseries[emg_idx[0]].peaks["emg_breaths"].peak_df["start_idx"].to_numpy()
)
# plt.close("all")
nrows = 3
ncols = 2
axes = plt.subplots(
    nrows=nrows, ncols=ncols, sharex=True, figsize=(ncols * 6, nrows * 2)
)[1]

axes_emg = axes[:, 0]
axes_vent = axes[:, 1]

emg_timeseries.plot_full(
    axes=axes_emg,
    baseline_bool=True,
)


vent_timeseries.plot_full(
    axes=axes_vent,
    baseline_bool=True,
)

emg_timeseries.plot_markers(
    peak_set_name=["Pocc", "Pocc", "Pocc"], axes=np.transpose([axes_emg])
)
vent_timeseries.plot_markers(
    peak_set_name=["Pocc", "Pocc", "Pocc"], axes=np.transpose([axes_vent]), colors="r"
)

axes_emg[0].set_title("EMG data")
axes_emg[-1].set_xlabel("t (s)")
axes_vent[0].set_title("Ventilator data")
axes_vent[-1].set_xlabel("t (s)")
plt.show()

In [ ]:
plt.close("all")
valid_peaks = (
    vent_timeseries[vent_timeseries.p_vent_idx]
    .peaks["Pocc"]
    .peak_df["valid"]
    .to_numpy()
)
n_peaks = len(valid_peaks)
# n_peaks = len(vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].peak_df["start_idx"].to_numpy())
vent_idx = [vent_timeseries.p_vent_idx, vent_timeseries.v_vent_idx]
n_peaks_to_plot = min(10, n_peaks)
if n_peaks:
    fig, axes = plt.subplots(
        nrows=4,
        ncols=n_peaks_to_plot,
        sharey="row",
        sharex="col",
        figsize=(6 * n_peaks_to_plot, 6),
        layout="constrained",
    )
    axes_emg = axes[:2, :] if n_peaks_to_plot > 1 else axes[:2]
    axes_vent = axes[2:, :] if n_peaks_to_plot > 1 else axes[2:]
    colors = ["tab:cyan", "tab:orange", "tab:red"]
    margin_s = 5  # margin in seconds around the peak to plot

    emg_timeseries.plot_peaks(
        channel_idxs=emg_idx,
        peak_set_name=["Pocc"],
        axes=axes_emg,
        colors=colors,
        valid_only=True,
        margin_s=margin_s * emg_timeseries.param["fs"],
        n_peaks_to_plot=n_peaks_to_plot,
    )

    emg_timeseries.plot_markers(
        channel_idxs=emg_idx,
        peak_set_name=["Pocc"],
        axes=axes_emg,
        valid_only=True,
        colors=colors,
        n_peaks_to_plot=n_peaks_to_plot,
    )

    for i in range(len(emg_idx)):
        axes_emg[i, 0].set_ylabel(emg_timeseries.labels[emg_idx[i]])

    vent_timeseries.plot_peaks(
        channel_idxs=vent_idx,
        peak_set_name=["Pocc"],
        axes=axes_vent,
        valid_only=True,
        colors=colors,
        margin_s=margin_s * vent_timeseries.param["fs"],
        n_peaks_to_plot=n_peaks_to_plot,
    )

    vent_timeseries.plot_markers(
        channel_idxs=vent_idx,
        peak_set_name=["Pocc"],
        axes=axes_vent,
        valid_only=True,
        colors=colors,
        n_peaks_to_plot=n_peaks_to_plot,
    )

    for i in range(len(vent_idx)):
        axes_vent[i, 0].set_ylabel(vent_timeseries.labels[vent_idx[i]])

    for i in range(n_peaks_to_plot):
        t_peak = (
            vent_timeseries[vent_timeseries.p_vent_idx]
            .peaks["Pocc"]
            .peak_df["peak_idx"]
            .to_numpy()[i]
            / vent_timeseries.param["fs"]
        )
        axes_emg[0, i].set_title(f"Peak {i + 1}\nt = {t_peak:.2f} s")

fig.canvas.header_visible = False  # drop the redundant title bar
fig.canvas.toolbar_visible = True  # pan/zoom/home toolbar
# fig

## ETP calculation

In [ ]:
emg_timeseries.calculate_time_products(
    channel_idxs=emg_idx,
    peak_set_name="Pocc",
    include_aub=True,
    aub_window_s=5 * emg_timeseries.param["fs"],
    parameter_name="ETP",
)

emg_timeseries.calculate_time_products(
    channel_idxs=emg_idx,
    peak_set_name="emg_breaths",
    include_aub=True,
    aub_window_s=5 * emg_timeseries.param["fs"],
    parameter_name="ETP",
)

In [ ]:
vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].peak_df

## Quality criteria

In [ ]:
for idx in emg_idx:
    # print(f"EMG channel: {emg_timeseries.labels[idx]}")
    emg_timeseries[idx].test_emg_quality(
        peak_set_name="Pocc", parameter_names={"time_product": "ETP"}, verbose=False
    )

    # emg_timeseries[idx].test_emg_quality(peak_set_name="emg_breaths",
    #                                     parameter_names={'time_product': 'ETP'},
    #                                     verbose=False)

vent_timeseries[vent_timeseries.p_vent_idx].test_pocc_quality(
    peak_set_name="Pocc", parameter_names={"time_product": "PTPocc"}, verbose=True
)

In [ ]:
peaks_pocc = (
    vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].peak_df.copy(deep=True)
)
peaks_pocc["duration_samples"] = peaks_pocc["end_idx"] - peaks_pocc["start_idx"]
peaks_pocc["peak_to_end_samples"] = peaks_pocc["end_idx"] - peaks_pocc["peak_idx"]

In [ ]:
peaks_pocc

# 5. Compute the NMC

In [ ]:
display("p_vent", vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].peak_df)
display(
    emg_timeseries.labels[emg_idx[0]], emg_timeseries[emg_idx[0]].peaks["Pocc"].peak_df
)
display(
    emg_timeseries.labels[emg_idx[1]], emg_timeseries[emg_idx[1]].peaks["Pocc"].peak_df
)

In [ ]:
vent_peaks = vent_timeseries[vent_timeseries.p_vent_idx].peaks["Pocc"].peak_df
PTPocc = np.abs(vent_peaks["PTPocc"].to_numpy())
valid_vent = vent_peaks["valid"].to_numpy()

NMC = pd.DataFrame(index=vent_peaks.index)
for idx in emg_idx:
    label = emg_timeseries.labels[idx]
    emg_peaks = emg_timeseries[idx].peaks["Pocc"].peak_df
    ETPocc = emg_peaks["ETP"].to_numpy()
    valid_emg = emg_peaks["valid"].to_numpy()

    NMC[(label, "NMC")] = PTPocc / ETPocc
    NMC[(label, "Valid")] = np.logical_and(valid_emg, valid_vent)

NMC.columns = pd.MultiIndex.from_tuples(NMC.columns)
NMC